import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const origin =
  typeof window !== 'undefined' && window.location.origin
      ? window.location.origin
      : '';
  
  const mode = origin.includes('dev') ? 'dev' : origin.includes('staging') ? 'staging' : 'prod'
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        this is {mode}
      </main>
    </>
  )
}
