import Head from 'next/head'
import { Inter } from 'next/font/google'
import useMode from '@/hooks/useMode'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const mode = useMode()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        this is {mode}
      </main>
    </>
  )
}
